// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: battle.proto

#ifndef PROTOBUF_battle_2eproto__INCLUDED
#define PROTOBUF_battle_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "share.pb.h"
// @@protoc_insertion_point(includes)

namespace battleproto {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_battle_2eproto();
void protobuf_AssignDesc_battle_2eproto();
void protobuf_ShutdownFile_battle_2eproto();

class BattleOp;
class MessageType;
class PBDelTroop;
class PBOpBattle;

enum MessageType_Cmd {
  MessageType_Cmd_StartCmd = 0,
  MessageType_Cmd_PBStartCmd = 9000,
  MessageType_Cmd_PBOpBattle = 9001,
  MessageType_Cmd_PBDelTroop = 9002,
  MessageType_Cmd_PBEndCmd = 9999,
  MessageType_Cmd_MessageType_Cmd_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  MessageType_Cmd_MessageType_Cmd_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool MessageType_Cmd_IsValid(int value);
const MessageType_Cmd MessageType_Cmd_Cmd_MIN = MessageType_Cmd_StartCmd;
const MessageType_Cmd MessageType_Cmd_Cmd_MAX = MessageType_Cmd_PBEndCmd;
const int MessageType_Cmd_Cmd_ARRAYSIZE = MessageType_Cmd_Cmd_MAX + 1;

const ::google::protobuf::EnumDescriptor* MessageType_Cmd_descriptor();
inline const ::std::string& MessageType_Cmd_Name(MessageType_Cmd value) {
  return ::google::protobuf::internal::NameOfEnum(
    MessageType_Cmd_descriptor(), value);
}
inline bool MessageType_Cmd_Parse(
    const ::std::string& name, MessageType_Cmd* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MessageType_Cmd>(
    MessageType_Cmd_descriptor(), name, value);
}
enum BattleOpType {
  NULL_ = 0,
  Attack = 1,
  Escape = 2,
  BattleOpType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  BattleOpType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool BattleOpType_IsValid(int value);
const BattleOpType BattleOpType_MIN = NULL_;
const BattleOpType BattleOpType_MAX = Escape;
const int BattleOpType_ARRAYSIZE = BattleOpType_MAX + 1;

const ::google::protobuf::EnumDescriptor* BattleOpType_descriptor();
inline const ::std::string& BattleOpType_Name(BattleOpType value) {
  return ::google::protobuf::internal::NameOfEnum(
    BattleOpType_descriptor(), value);
}
inline bool BattleOpType_Parse(
    const ::std::string& name, BattleOpType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<BattleOpType>(
    BattleOpType_descriptor(), name, value);
}
// ===================================================================

class MessageType : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:battleproto.MessageType) */ {
 public:
  MessageType();
  virtual ~MessageType();

  MessageType(const MessageType& from);

  inline MessageType& operator=(const MessageType& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageType& default_instance();

  void Swap(MessageType* other);

  // implements Message ----------------------------------------------

  inline MessageType* New() const { return New(NULL); }

  MessageType* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageType& from);
  void MergeFrom(const MessageType& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MessageType* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef MessageType_Cmd Cmd;
  static const Cmd StartCmd =
    MessageType_Cmd_StartCmd;
  static const Cmd PBStartCmd =
    MessageType_Cmd_PBStartCmd;
  static const Cmd PBOpBattle =
    MessageType_Cmd_PBOpBattle;
  static const Cmd PBDelTroop =
    MessageType_Cmd_PBDelTroop;
  static const Cmd PBEndCmd =
    MessageType_Cmd_PBEndCmd;
  static inline bool Cmd_IsValid(int value) {
    return MessageType_Cmd_IsValid(value);
  }
  static const Cmd Cmd_MIN =
    MessageType_Cmd_Cmd_MIN;
  static const Cmd Cmd_MAX =
    MessageType_Cmd_Cmd_MAX;
  static const int Cmd_ARRAYSIZE =
    MessageType_Cmd_Cmd_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Cmd_descriptor() {
    return MessageType_Cmd_descriptor();
  }
  static inline const ::std::string& Cmd_Name(Cmd value) {
    return MessageType_Cmd_Name(value);
  }
  static inline bool Cmd_Parse(const ::std::string& name,
      Cmd* value) {
    return MessageType_Cmd_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:battleproto.MessageType)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_battle_2eproto();
  friend void protobuf_AssignDesc_battle_2eproto();
  friend void protobuf_ShutdownFile_battle_2eproto();

  void InitAsDefaultInstance();
  static MessageType* default_instance_;
};
// -------------------------------------------------------------------

class BattleOp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:battleproto.BattleOp) */ {
 public:
  BattleOp();
  virtual ~BattleOp();

  BattleOp(const BattleOp& from);

  inline BattleOp& operator=(const BattleOp& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BattleOp& default_instance();

  void Swap(BattleOp* other);

  // implements Message ----------------------------------------------

  inline BattleOp* New() const { return New(NULL); }

  BattleOp* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BattleOp& from);
  void MergeFrom(const BattleOp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(BattleOp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .battleproto.BattleOpType op_type = 1;
  void clear_op_type();
  static const int kOpTypeFieldNumber = 1;
  ::battleproto::BattleOpType op_type() const;
  void set_op_type(::battleproto::BattleOpType value);

  // optional uint64 troop_a_id = 2;
  void clear_troop_a_id();
  static const int kTroopAIdFieldNumber = 2;
  ::google::protobuf::uint64 troop_a_id() const;
  void set_troop_a_id(::google::protobuf::uint64 value);

  // optional uint64 troop_b_id = 3;
  void clear_troop_b_id();
  static const int kTroopBIdFieldNumber = 3;
  ::google::protobuf::uint64 troop_b_id() const;
  void set_troop_b_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:battleproto.BattleOp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 troop_a_id_;
  ::google::protobuf::uint64 troop_b_id_;
  int op_type_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_battle_2eproto();
  friend void protobuf_AssignDesc_battle_2eproto();
  friend void protobuf_ShutdownFile_battle_2eproto();

  void InitAsDefaultInstance();
  static BattleOp* default_instance_;
};
// -------------------------------------------------------------------

class PBOpBattle : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:battleproto.PBOpBattle) */ {
 public:
  PBOpBattle();
  virtual ~PBOpBattle();

  PBOpBattle(const PBOpBattle& from);

  inline PBOpBattle& operator=(const PBOpBattle& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBOpBattle& default_instance();

  void Swap(PBOpBattle* other);

  // implements Message ----------------------------------------------

  inline PBOpBattle* New() const { return New(NULL); }

  PBOpBattle* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PBOpBattle& from);
  void MergeFrom(const PBOpBattle& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PBOpBattle* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .battleproto.BattleOp op = 1;
  int op_size() const;
  void clear_op();
  static const int kOpFieldNumber = 1;
  const ::battleproto::BattleOp& op(int index) const;
  ::battleproto::BattleOp* mutable_op(int index);
  ::battleproto::BattleOp* add_op();
  ::google::protobuf::RepeatedPtrField< ::battleproto::BattleOp >*
      mutable_op();
  const ::google::protobuf::RepeatedPtrField< ::battleproto::BattleOp >&
      op() const;

  // repeated .shareproto.TroopDetailInfo troop_info = 2;
  int troop_info_size() const;
  void clear_troop_info();
  static const int kTroopInfoFieldNumber = 2;
  const ::shareproto::TroopDetailInfo& troop_info(int index) const;
  ::shareproto::TroopDetailInfo* mutable_troop_info(int index);
  ::shareproto::TroopDetailInfo* add_troop_info();
  ::google::protobuf::RepeatedPtrField< ::shareproto::TroopDetailInfo >*
      mutable_troop_info();
  const ::google::protobuf::RepeatedPtrField< ::shareproto::TroopDetailInfo >&
      troop_info() const;

  // @@protoc_insertion_point(class_scope:battleproto.PBOpBattle)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::battleproto::BattleOp > op_;
  ::google::protobuf::RepeatedPtrField< ::shareproto::TroopDetailInfo > troop_info_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_battle_2eproto();
  friend void protobuf_AssignDesc_battle_2eproto();
  friend void protobuf_ShutdownFile_battle_2eproto();

  void InitAsDefaultInstance();
  static PBOpBattle* default_instance_;
};
// -------------------------------------------------------------------

class PBDelTroop : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:battleproto.PBDelTroop) */ {
 public:
  PBDelTroop();
  virtual ~PBDelTroop();

  PBDelTroop(const PBDelTroop& from);

  inline PBDelTroop& operator=(const PBDelTroop& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBDelTroop& default_instance();

  void Swap(PBDelTroop* other);

  // implements Message ----------------------------------------------

  inline PBDelTroop* New() const { return New(NULL); }

  PBDelTroop* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PBDelTroop& from);
  void MergeFrom(const PBDelTroop& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PBDelTroop* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint64 troop_id = 1;
  int troop_id_size() const;
  void clear_troop_id();
  static const int kTroopIdFieldNumber = 1;
  ::google::protobuf::uint64 troop_id(int index) const;
  void set_troop_id(int index, ::google::protobuf::uint64 value);
  void add_troop_id(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      troop_id() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_troop_id();

  // @@protoc_insertion_point(class_scope:battleproto.PBDelTroop)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > troop_id_;
  mutable int _troop_id_cached_byte_size_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_battle_2eproto();
  friend void protobuf_AssignDesc_battle_2eproto();
  friend void protobuf_ShutdownFile_battle_2eproto();

  void InitAsDefaultInstance();
  static PBDelTroop* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// MessageType

// -------------------------------------------------------------------

// BattleOp

// optional .battleproto.BattleOpType op_type = 1;
inline void BattleOp::clear_op_type() {
  op_type_ = 0;
}
inline ::battleproto::BattleOpType BattleOp::op_type() const {
  // @@protoc_insertion_point(field_get:battleproto.BattleOp.op_type)
  return static_cast< ::battleproto::BattleOpType >(op_type_);
}
inline void BattleOp::set_op_type(::battleproto::BattleOpType value) {
  
  op_type_ = value;
  // @@protoc_insertion_point(field_set:battleproto.BattleOp.op_type)
}

// optional uint64 troop_a_id = 2;
inline void BattleOp::clear_troop_a_id() {
  troop_a_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BattleOp::troop_a_id() const {
  // @@protoc_insertion_point(field_get:battleproto.BattleOp.troop_a_id)
  return troop_a_id_;
}
inline void BattleOp::set_troop_a_id(::google::protobuf::uint64 value) {
  
  troop_a_id_ = value;
  // @@protoc_insertion_point(field_set:battleproto.BattleOp.troop_a_id)
}

// optional uint64 troop_b_id = 3;
inline void BattleOp::clear_troop_b_id() {
  troop_b_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BattleOp::troop_b_id() const {
  // @@protoc_insertion_point(field_get:battleproto.BattleOp.troop_b_id)
  return troop_b_id_;
}
inline void BattleOp::set_troop_b_id(::google::protobuf::uint64 value) {
  
  troop_b_id_ = value;
  // @@protoc_insertion_point(field_set:battleproto.BattleOp.troop_b_id)
}

// -------------------------------------------------------------------

// PBOpBattle

// repeated .battleproto.BattleOp op = 1;
inline int PBOpBattle::op_size() const {
  return op_.size();
}
inline void PBOpBattle::clear_op() {
  op_.Clear();
}
inline const ::battleproto::BattleOp& PBOpBattle::op(int index) const {
  // @@protoc_insertion_point(field_get:battleproto.PBOpBattle.op)
  return op_.Get(index);
}
inline ::battleproto::BattleOp* PBOpBattle::mutable_op(int index) {
  // @@protoc_insertion_point(field_mutable:battleproto.PBOpBattle.op)
  return op_.Mutable(index);
}
inline ::battleproto::BattleOp* PBOpBattle::add_op() {
  // @@protoc_insertion_point(field_add:battleproto.PBOpBattle.op)
  return op_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::battleproto::BattleOp >*
PBOpBattle::mutable_op() {
  // @@protoc_insertion_point(field_mutable_list:battleproto.PBOpBattle.op)
  return &op_;
}
inline const ::google::protobuf::RepeatedPtrField< ::battleproto::BattleOp >&
PBOpBattle::op() const {
  // @@protoc_insertion_point(field_list:battleproto.PBOpBattle.op)
  return op_;
}

// repeated .shareproto.TroopDetailInfo troop_info = 2;
inline int PBOpBattle::troop_info_size() const {
  return troop_info_.size();
}
inline void PBOpBattle::clear_troop_info() {
  troop_info_.Clear();
}
inline const ::shareproto::TroopDetailInfo& PBOpBattle::troop_info(int index) const {
  // @@protoc_insertion_point(field_get:battleproto.PBOpBattle.troop_info)
  return troop_info_.Get(index);
}
inline ::shareproto::TroopDetailInfo* PBOpBattle::mutable_troop_info(int index) {
  // @@protoc_insertion_point(field_mutable:battleproto.PBOpBattle.troop_info)
  return troop_info_.Mutable(index);
}
inline ::shareproto::TroopDetailInfo* PBOpBattle::add_troop_info() {
  // @@protoc_insertion_point(field_add:battleproto.PBOpBattle.troop_info)
  return troop_info_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::shareproto::TroopDetailInfo >*
PBOpBattle::mutable_troop_info() {
  // @@protoc_insertion_point(field_mutable_list:battleproto.PBOpBattle.troop_info)
  return &troop_info_;
}
inline const ::google::protobuf::RepeatedPtrField< ::shareproto::TroopDetailInfo >&
PBOpBattle::troop_info() const {
  // @@protoc_insertion_point(field_list:battleproto.PBOpBattle.troop_info)
  return troop_info_;
}

// -------------------------------------------------------------------

// PBDelTroop

// repeated uint64 troop_id = 1;
inline int PBDelTroop::troop_id_size() const {
  return troop_id_.size();
}
inline void PBDelTroop::clear_troop_id() {
  troop_id_.Clear();
}
inline ::google::protobuf::uint64 PBDelTroop::troop_id(int index) const {
  // @@protoc_insertion_point(field_get:battleproto.PBDelTroop.troop_id)
  return troop_id_.Get(index);
}
inline void PBDelTroop::set_troop_id(int index, ::google::protobuf::uint64 value) {
  troop_id_.Set(index, value);
  // @@protoc_insertion_point(field_set:battleproto.PBDelTroop.troop_id)
}
inline void PBDelTroop::add_troop_id(::google::protobuf::uint64 value) {
  troop_id_.Add(value);
  // @@protoc_insertion_point(field_add:battleproto.PBDelTroop.troop_id)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
PBDelTroop::troop_id() const {
  // @@protoc_insertion_point(field_list:battleproto.PBDelTroop.troop_id)
  return troop_id_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
PBDelTroop::mutable_troop_id() {
  // @@protoc_insertion_point(field_mutable_list:battleproto.PBDelTroop.troop_id)
  return &troop_id_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace battleproto

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::battleproto::MessageType_Cmd> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::battleproto::MessageType_Cmd>() {
  return ::battleproto::MessageType_Cmd_descriptor();
}
template <> struct is_proto_enum< ::battleproto::BattleOpType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::battleproto::BattleOpType>() {
  return ::battleproto::BattleOpType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_battle_2eproto__INCLUDED
