#!/usr/bin/bash
touch distcc.log
export DISTCC_HOSTS="localhost 192.168.2.236 192.168.2.238 "
export DISTCC_POTENTIAL_HOSTS="localhost 192.168.2.236 192.168.2.238"
export DISTCC_LOG="./distcc.log"
mkdir build
cd build
cmake -DCMAKE_C_COMPILER=/usr/lib/distcc/cc -DCMAKE_CXX_COMPILER=/usr/lib/distcc/g++ ../
pump make -j12
